### ISSUE TITLE
The game behaves unexpectedly when the two balls are separated. (Possible bug)

### ISSUE THREAD

**Issue by samagra14** [rheaparekh/jezzball-clone#8]
Every time I try to trap the two balls separately within two different containers, The above container goes full shaded and after that, the game stops.
![image](https://user-images.githubusercontent.com/25154317/29492412-612c2460-8598-11e7-9be7-94e76442f969.png)
### In the second image I tried clicking many columns and the game behaviour was unexpected as it shaded only that particular column. You can see the weird pattern I made out there
![image](https://user-images.githubusercontent.com/25154317/29492437-ed18cc6c-8598-11e7-97f5-cfed5616c577.png)

**Comment by rheaparekh** [comment]
![sourced](https://user-images.githubusercontent.com/25330892/36713529-2b1e26cc-1bb4-11e8-8d40-eebc3221a4cb.gif)
